apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-knative-domain.yaml
    target:
      kind: ConfigMap
      name: config-domain
      namespace: knative-serving
